name: 'Sync Upstream PR'
description: 'Sync fork with upstream repository via Pull Request or direct push'
author: 'kuma0128'

branding:
  icon: 'git-pull-request'
  color: 'blue'

inputs:
  upstream_repo:
    description: 'Upstream repository (e.g., awslabs/ssosync)'
    required: true
  upstream_branch:
    description: 'Upstream branch to sync from'
    required: false
    default: 'main'
  target_branch:
    description: 'Target branch to sync to'
    required: false
    default: 'main'
  mode:
    description: 'Sync mode: "pr" creates a Pull Request, "direct" pushes directly to target branch'
    required: false
    default: 'pr'
  pr_title:
    description: 'Pull request title'
    required: false
    default: 'chore: Sync with upstream'
  pr_body:
    description: 'Pull request body'
    required: false
    default: ''
  pr_labels:
    description: 'Comma-separated labels for the PR'
    required: false
    default: 'upstream-sync'
  token:
    description: 'GitHub token with repo and pull-request permissions'
    required: true

outputs:
  has_changes:
    description: 'Whether there are changes to sync'
    value: ${{ steps.check.outputs.has_changes }}
  commits:
    description: 'Number of commits behind upstream'
    value: ${{ steps.check.outputs.commits }}
  pr_number:
    description: 'Created PR number (if any)'
    value: ${{ steps.create-pr.outputs.pr_number }}
  pr_url:
    description: 'Created PR URL (if any)'
    value: ${{ steps.create-pr.outputs.pr_url }}
  skipped:
    description: 'Whether PR creation was skipped due to existing open PR'
    value: ${{ steps.create-pr.outputs.skipped }}

runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      shell: bash
      env:
        MODE: ${{ inputs.mode }}
        UPSTREAM_REPO: ${{ inputs.upstream_repo }}
      run: |
        if [[ "$MODE" != "pr" && "$MODE" != "direct" ]]; then
          echo "::error::Invalid mode '$MODE'. Must be 'pr' or 'direct'."
          exit 1
        fi

        # Validate upstream_repo format (owner/repo)
        # GitHub usernames: alphanumeric or hyphens, cannot start/end with hyphen
        # GitHub repo names: alphanumeric, hyphens, underscores, periods, cannot start with period
        if [[ ! "$UPSTREAM_REPO" =~ ^[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?/[a-zA-Z0-9_][a-zA-Z0-9._-]*$ ]]; then
          echo "::error::Invalid upstream_repo format '$UPSTREAM_REPO'. Expected 'owner/repo'."
          exit 1
        fi

    - name: Configure git
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Fetch upstream
      shell: bash
      env:
        UPSTREAM_REPO: ${{ inputs.upstream_repo }}
        UPSTREAM_BRANCH: ${{ inputs.upstream_branch }}
      run: |
        UPSTREAM_URL="https://github.com/${UPSTREAM_REPO}.git"

        # Ensure upstream remote points to the correct URL
        if git remote get-url upstream &>/dev/null; then
          CURRENT_URL=$(git remote get-url upstream)
          if [[ "$CURRENT_URL" != "$UPSTREAM_URL" ]]; then
            echo "::notice::Updating upstream remote URL from $CURRENT_URL to $UPSTREAM_URL"
            git remote set-url upstream "$UPSTREAM_URL"
          fi
        else
          git remote add upstream "$UPSTREAM_URL"
        fi

        if ! git fetch upstream "$UPSTREAM_BRANCH"; then
          echo "::error::Failed to fetch upstream/$UPSTREAM_BRANCH from $UPSTREAM_REPO"
          exit 1
        fi

    - name: Check for changes
      id: check
      shell: bash
      env:
        UPSTREAM_BRANCH: ${{ inputs.upstream_branch }}
      run: |
        if ! DIFF=$(git rev-list --count HEAD.."upstream/$UPSTREAM_BRANCH"); then
          echo "::error::Failed to compare with upstream/$UPSTREAM_BRANCH"
          exit 1
        fi
        echo "commits=$DIFF" >> $GITHUB_OUTPUT
        if [ "$DIFF" -gt 0 ]; then
          echo "has_changes=true" >> $GITHUB_OUTPUT
          echo "::notice::Found $DIFF new commits from upstream"
        else
          echo "has_changes=false" >> $GITHUB_OUTPUT
          echo "::notice::Already up to date with upstream"
        fi

    - name: Direct push to target branch
      id: direct-push
      if: steps.check.outputs.has_changes == 'true' && inputs.mode == 'direct'
      shell: bash
      env:
        UPSTREAM_BRANCH: ${{ inputs.upstream_branch }}
        TARGET_BRANCH: ${{ inputs.target_branch }}
      run: |
        # Ensure we are on the target branch (handles detached HEAD state)
        CURRENT_BRANCH=$(git branch --show-current)
        if [[ -z "$CURRENT_BRANCH" || "$CURRENT_BRANCH" != "$TARGET_BRANCH" ]]; then
          echo "::notice::Switching to '$TARGET_BRANCH'"
          if ! git checkout -B "$TARGET_BRANCH" "origin/$TARGET_BRANCH"; then
            echo "::error::Failed to checkout $TARGET_BRANCH"
            exit 1
          fi
        fi

        # Merge upstream changes directly
        if git merge "upstream/$UPSTREAM_BRANCH" --no-edit; then
          if ! git push origin "$TARGET_BRANCH"; then
            echo "::error::Failed to push to $TARGET_BRANCH"
            exit 1
          fi
          echo "::notice::Successfully synced with upstream (direct push)"
        else
          echo "::error::Merge conflicts detected - cannot push directly. Consider using mode: pr"
          git merge --abort
          exit 1
        fi

    - name: Create sync branch and PR
      id: create-pr
      if: steps.check.outputs.has_changes == 'true' && inputs.mode == 'pr'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        UPSTREAM_REPO: ${{ inputs.upstream_repo }}
        UPSTREAM_BRANCH: ${{ inputs.upstream_branch }}
        TARGET_BRANCH: ${{ inputs.target_branch }}
        PR_TITLE: ${{ inputs.pr_title }}
        PR_BODY_INPUT: ${{ inputs.pr_body }}
        PR_LABELS: ${{ inputs.pr_labels }}
        COMMITS_COUNT: ${{ steps.check.outputs.commits }}
        RUN_ID: ${{ github.run_id }}
        RUN_ATTEMPT: ${{ github.run_attempt }}
      run: |
        # Check for existing open sync PRs using the first configured label
        FIRST_LABEL=""
        if [ -n "$PR_LABELS" ]; then
          FIRST_LABEL=$(echo "$PR_LABELS" | cut -d',' -f1 | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
        fi

        if [ -n "$FIRST_LABEL" ]; then
          set +e
          EXISTING_PR_NUMBER=$(gh pr list --base "$TARGET_BRANCH" --label "$FIRST_LABEL" --state open --json number --jq '.[0].number' 2>/dev/null)
          GH_EXIT_CODE=$?
          set -e

          if [ $GH_EXIT_CODE -ne 0 ]; then
            echo "::warning::Failed to check for existing PRs - proceeding with PR creation"
          elif [ -n "$EXISTING_PR_NUMBER" ] && [ "$EXISTING_PR_NUMBER" != "null" ]; then
            set +e
            EXISTING_PR_URL=$(gh pr view "$EXISTING_PR_NUMBER" --json url --jq '.url' 2>/dev/null)
            VIEW_EXIT_CODE=$?
            set -e

            if [ $VIEW_EXIT_CODE -ne 0 ]; then
              echo "::warning::Failed to get existing PR details - proceeding with PR creation"
            else
              echo "::notice::Existing upstream sync PR found: $EXISTING_PR_URL - skipping PR creation"
              echo "pr_url=$EXISTING_PR_URL" >> $GITHUB_OUTPUT
              echo "pr_number=$EXISTING_PR_NUMBER" >> $GITHUB_OUTPUT
              echo "skipped=true" >> $GITHUB_OUTPUT
              exit 0
            fi
          fi
        fi

        SYNC_BRANCH="sync-upstream-${RUN_ID}-${RUN_ATTEMPT}"

        # Create and checkout sync branch
        git checkout -b "$SYNC_BRANCH"

        # Merge upstream changes
        if git merge "upstream/$UPSTREAM_BRANCH" --no-edit; then
          echo "::notice::Merged upstream changes successfully"
          HAS_CONFLICTS="false"
        else
          echo "::warning::Merge conflicts detected - PR will need manual resolution"
          HAS_CONFLICTS="true"

          # Stage all files including those with conflict markers
          git add -A

          # Check if there are staged changes to commit
          if git diff --cached --quiet; then
            echo "::error::No changes staged after merge conflict - cannot create PR"
            exit 1
          fi

          # Commit with conflict markers for manual resolution
          if ! git commit -m "chore: sync with upstream (conflicts need resolution)" --no-verify; then
            echo "::error::Failed to commit merge conflict state"
            exit 1
          fi
        fi

        # Push the branch
        if ! git push origin "$SYNC_BRANCH"; then
          echo "::error::Failed to push branch $SYNC_BRANCH"
          exit 1
        fi

        # Build PR body
        if [ -z "$PR_BODY_INPUT" ]; then
          PR_BODY="## Upstream Sync

This PR syncs changes from [\`${UPSTREAM_REPO}\`](https://github.com/${UPSTREAM_REPO}).

**Commits to sync:** ${COMMITS_COUNT}
**Source branch:** \`${UPSTREAM_BRANCH}\`
**Target branch:** \`${TARGET_BRANCH}\`"

          if [ "$HAS_CONFLICTS" = "true" ]; then
            PR_BODY="${PR_BODY}

> [!WARNING]
> Merge conflicts were detected. Please resolve them manually before merging."
          fi
        else
          PR_BODY="$PR_BODY_INPUT"
        fi

        # Create PR with labels
        LABEL_ARGS=()
        if [ -n "$PR_LABELS" ]; then
          IFS=',' read -ra LABEL_ARRAY <<< "$PR_LABELS"
          for label in "${LABEL_ARRAY[@]}"; do
            # Trim whitespace without xargs (handles special characters safely)
            trimmed=$(echo "$label" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
            if [ -n "$trimmed" ]; then
              LABEL_ARGS+=(--label "$trimmed")
            fi
          done
        fi

        # Create PR and capture stdout/stderr separately
        PR_STDERR_FILE=$(mktemp)
        set +e
        PR_URL=$(gh pr create \
          --title "$PR_TITLE" \
          --body "$PR_BODY" \
          --base "$TARGET_BRANCH" \
          --head "$SYNC_BRANCH" \
          "${LABEL_ARGS[@]}" 2>"$PR_STDERR_FILE")
        PR_EXIT_CODE=$?
        set -e

        if [ $PR_EXIT_CODE -ne 0 ]; then
          PR_ERROR=$(cat "$PR_STDERR_FILE")
          rm -f "$PR_STDERR_FILE"
          echo "::error::Failed to create PR: $PR_ERROR"
          exit 1
        fi
        rm -f "$PR_STDERR_FILE"

        # Remove any trailing whitespace/newlines from URL
        PR_URL=$(echo "$PR_URL" | tr -d '\n\r')

        # Validate URL format and extract PR number
        if [[ "$PR_URL" =~ ^https://github\.com/.+/pull/([0-9]+)$ ]]; then
          PR_NUMBER="${BASH_REMATCH[1]}"
          echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
          echo "::notice::Created PR: $PR_URL"
        else
          echo "::error::Unexpected PR URL format: $PR_URL"
          exit 1
        fi
