name: 'Sync Upstream PR'
description: 'Sync fork with upstream repository via Pull Request or direct push'
author: 'kuma0128'

branding:
  icon: 'git-pull-request'
  color: 'blue'

inputs:
  upstream_repo:
    description: 'Upstream repository (e.g., awslabs/ssosync)'
    required: true
  upstream_branch:
    description: 'Upstream branch to sync from'
    required: false
    default: 'main'
  target_branch:
    description: 'Target branch to sync to'
    required: false
    default: 'main'
  mode:
    description: 'Sync mode: "pr" creates a Pull Request, "direct" pushes directly to target branch'
    required: false
    default: 'pr'
  pr_title:
    description: 'Pull request title'
    required: false
    default: 'chore: Sync with upstream'
  pr_body:
    description: 'Pull request body'
    required: false
    default: ''
  pr_labels:
    description: 'Comma-separated labels for the PR'
    required: false
    default: 'upstream-sync'
  token:
    description: 'GitHub token with repo and pull-request permissions'
    required: true

outputs:
  has_changes:
    description: 'Whether there are changes to sync'
    value: ${{ steps.check.outputs.has_changes }}
  commits:
    description: 'Number of commits behind upstream'
    value: ${{ steps.check.outputs.commits }}
  pr_number:
    description: 'Created PR number (if any)'
    value: ${{ steps.create-pr.outputs.pr_number }}
  pr_url:
    description: 'Created PR URL (if any)'
    value: ${{ steps.create-pr.outputs.pr_url }}

runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        if [[ "${{ inputs.mode }}" != "pr" && "${{ inputs.mode }}" != "direct" ]]; then
          echo "::error::Invalid mode '${{ inputs.mode }}'. Must be 'pr' or 'direct'."
          exit 1
        fi

    - name: Configure git
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Fetch upstream
      shell: bash
      run: |
        git remote add upstream "https://github.com/${{ inputs.upstream_repo }}.git" 2>/dev/null || true
        if ! git fetch upstream "${{ inputs.upstream_branch }}"; then
          echo "::error::Failed to fetch upstream/${{ inputs.upstream_branch }} from ${{ inputs.upstream_repo }}"
          exit 1
        fi

    - name: Check for changes
      id: check
      shell: bash
      run: |
        if ! DIFF=$(git rev-list --count HEAD.."upstream/${{ inputs.upstream_branch }}"); then
          echo "::error::Failed to compare with upstream/${{ inputs.upstream_branch }}"
          exit 1
        fi
        echo "commits=$DIFF" >> $GITHUB_OUTPUT
        if [ "$DIFF" -gt 0 ]; then
          echo "has_changes=true" >> $GITHUB_OUTPUT
          echo "::notice::Found $DIFF new commits from upstream"
        else
          echo "has_changes=false" >> $GITHUB_OUTPUT
          echo "::notice::Already up to date with upstream"
        fi

    - name: Direct push to target branch
      id: direct-push
      if: steps.check.outputs.has_changes == 'true' && inputs.mode == 'direct'
      shell: bash
      run: |
        # Merge upstream changes directly
        if git merge "upstream/${{ inputs.upstream_branch }}" --no-edit; then
          if ! git push origin "${{ inputs.target_branch }}"; then
            echo "::error::Failed to push to ${{ inputs.target_branch }}"
            exit 1
          fi
          echo "::notice::Successfully synced with upstream (direct push)"
        else
          echo "::error::Merge conflicts detected - cannot push directly. Consider using mode: pr"
          exit 1
        fi

    - name: Create sync branch and PR
      id: create-pr
      if: steps.check.outputs.has_changes == 'true' && inputs.mode == 'pr'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        SYNC_BRANCH="sync-upstream-$(date +%Y%m%d-%H%M%S)-$RANDOM"

        # Create and checkout sync branch
        git checkout -b "$SYNC_BRANCH"

        # Merge upstream changes
        if git merge "upstream/${{ inputs.upstream_branch }}" --no-edit; then
          echo "::notice::Merged upstream changes successfully"
          HAS_CONFLICTS="false"
        else
          echo "::warning::Merge conflicts detected - PR will need manual resolution"
          HAS_CONFLICTS="true"

          # Stage all files including those with conflict markers
          git add -A

          # Check if there are staged changes to commit
          if git diff --cached --quiet; then
            echo "::error::No changes staged after merge conflict - cannot create PR"
            exit 1
          fi

          # Commit with conflict markers for manual resolution
          if ! git commit -m "chore: sync with upstream (conflicts need resolution)" --no-verify; then
            echo "::error::Failed to commit merge conflict state"
            exit 1
          fi
        fi

        # Push the branch
        if ! git push origin "$SYNC_BRANCH"; then
          echo "::error::Failed to push branch $SYNC_BRANCH"
          exit 1
        fi

        # Build PR body
        PR_BODY="${{ inputs.pr_body }}"
        if [ -z "$PR_BODY" ]; then
          PR_BODY=$(cat <<EOF
## Upstream Sync

This PR syncs changes from [\`${{ inputs.upstream_repo }}\`](https://github.com/${{ inputs.upstream_repo }}).

**Commits to sync:** ${{ steps.check.outputs.commits }}
**Source branch:** \`${{ inputs.upstream_branch }}\`
**Target branch:** \`${{ inputs.target_branch }}\`
EOF
)
          if [ "$HAS_CONFLICTS" = "true" ]; then
            PR_BODY=$(cat <<EOF
$PR_BODY

> [!WARNING]
> Merge conflicts were detected. Please resolve them manually before merging.
EOF
)
          fi
        fi

        # Create PR with labels
        LABELS="${{ inputs.pr_labels }}"
        LABEL_ARGS=()
        if [ -n "$LABELS" ]; then
          IFS=',' read -ra LABEL_ARRAY <<< "$LABELS"
          for label in "${LABEL_ARRAY[@]}"; do
            trimmed=$(echo "$label" | xargs)
            if [ -n "$trimmed" ]; then
              LABEL_ARGS+=(--label "$trimmed")
            fi
          done
        fi

        PR_OUTPUT=$(gh pr create \
          --title "${{ inputs.pr_title }}" \
          --body "$PR_BODY" \
          --base "${{ inputs.target_branch }}" \
          --head "$SYNC_BRANCH" \
          "${LABEL_ARGS[@]}" 2>&1)
        PR_EXIT_CODE=$?

        if [ $PR_EXIT_CODE -eq 0 ] && [[ "$PR_OUTPUT" == https* ]]; then
          PR_NUMBER=$(echo "$PR_OUTPUT" | grep -oE '[0-9]+$')
          echo "pr_url=$PR_OUTPUT" >> $GITHUB_OUTPUT
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
          echo "::notice::Created PR: $PR_OUTPUT"
        else
          echo "::error::Failed to create PR: $PR_OUTPUT"
          exit 1
        fi
